# Mindrian System Prompts
from .larry_core import LARRY_RAG_SYSTEM_PROMPT
from .tta_workshop import TTA_WORKSHOP_PROMPT
from .jtbd_workshop import JTBD_WORKSHOP_PROMPT
from .scurve_workshop import SCURVE_WORKSHOP_PROMPT
from .redteam import REDTEAM_PROMPT
from .ackoff_workshop import ACKOFF_WORKSHOP_PROMPT
from .bono_master import BONO_MASTER_PROMPT
from .known_unknowns import KNOWN_UNKNOWNS_PROMPT
from .domain_explorer import DOMAIN_EXPLORER_PROMPT
from .pws_investment import PWS_INVESTMENT_PROMPT
from .scenario_analysis import SCENARIO_ANALYSIS_PROMPT
from .problem_classifier import PROBLEM_CLASSIFIER_PROMPT
from .multi_perspective_validation import (
    MULTI_PERSPECTIVE_VALIDATION_PROMPT,
    DOMAIN_EXTRACTION_PROMPT as MPV_DOMAIN_EXTRACTION,
    PERSONA_CONSTRUCTION_PROMPT as MPV_PERSONA_CONSTRUCTION,
    PARALLEL_RESEARCH_PROMPTS as MPV_RESEARCH_PROMPTS,
    STRUCTURED_DEBATE_PROMPT as MPV_DEBATE_PROMPT,
    VALIDATION_REPORT_PROMPT as MPV_REPORT_PROMPT,
)
from .beautiful_question import (
    BEAUTIFUL_QUESTION_PROMPT,
    WHY_PHASE_PROMPT as BQ_WHY_PROMPT,
    WHAT_IF_PHASE_PROMPT as BQ_WHAT_IF_PROMPT,
    HOW_PHASE_PROMPT as BQ_HOW_PROMPT,
)

from .cv_domain_prompts import (
    CV_EXTRACTION_PROMPT,
    DOMAIN_GENERATION_PROMPT,
    DOMAIN_SCORING_PROMPT,
)

from .research_domain_prompts import (
    RESEARCH_EXTRACTION_PROMPT,
    RESEARCH_QUESTION_EXPANSION_PROMPT,
    DOMAIN_GENERATION_FROM_RESEARCH_PROMPT,
    RESEARCH_DOMAIN_SCORING_PROMPT,
    RESEARCH_TRANSLATION_PROMPT,
)

__all__ = [
    "LARRY_RAG_SYSTEM_PROMPT",
    "TTA_WORKSHOP_PROMPT",
    "JTBD_WORKSHOP_PROMPT",
    "SCURVE_WORKSHOP_PROMPT",
    "REDTEAM_PROMPT",
    "ACKOFF_WORKSHOP_PROMPT",
    "BONO_MASTER_PROMPT",
    "KNOWN_UNKNOWNS_PROMPT",
    "DOMAIN_EXPLORER_PROMPT",
    "PWS_INVESTMENT_PROMPT",
    "SCENARIO_ANALYSIS_PROMPT",
    "PROBLEM_CLASSIFIER_PROMPT",
    "CV_EXTRACTION_PROMPT",
    "DOMAIN_GENERATION_PROMPT",
    "DOMAIN_SCORING_PROMPT",
    "RESEARCH_EXTRACTION_PROMPT",
    "RESEARCH_QUESTION_EXPANSION_PROMPT",
    "DOMAIN_GENERATION_FROM_RESEARCH_PROMPT",
    "RESEARCH_DOMAIN_SCORING_PROMPT",
    "RESEARCH_TRANSLATION_PROMPT",
    "MULTI_PERSPECTIVE_VALIDATION_PROMPT",
    "BEAUTIFUL_QUESTION_PROMPT",
]
