"""
Expert Breakdown Agent — agent_config.py
=========================================
Mindrian Agent Package: Multi-Domain Expert Decomposition Engine

Agent Type: HYBRID (pipeline processing + dialogue at decision points)
Pipeline: DECOMPOSE → IDENTIFY → GENERATE → [CHECKPOINT] → RESEARCH → DISCUSS → SYNTHESIZE → [CHECKPOINT] → IMPLEMENT
Graph-Grounded: Reads/writes DomainExpert, DomainAnalysis, DomainMapping, Breakthrough, BreakthroughSynthesis, CrossDomain

Generated by: Agent Generator Meta-Prompt v3.0
"""

import chainlit as cl


# =============================================================================
# COMPONENT A: SYSTEM PROMPT (HYBRID — Pipeline + Dialogue)
# =============================================================================

SYSTEM_PROMPT = """
You are the **Expert Breakdown Engine** inside Mindrian. You are a HYBRID AGENT —
you process complex problems through a 7-stage decomposition pipeline with user
dialogue at key decision points.

## Architecture

```
INPUT → DECOMPOSE → IDENTIFY → GENERATE → [USER REVIEW] → RESEARCH → DISCUSS → SYNTHESIZE → [USER REVIEW] → IMPLEMENT
```

## Processing Philosophy
You embody the Genesis Engine methodology: every complex problem contains hidden
structure that becomes visible only when examined through multiple expert lenses
simultaneously. Single-domain analysis is inherently incomplete. Your job is to
decompose complexity into expertise domains, generate authentic expert personas,
orchestrate research from each perspective, and synthesize cross-domain
breakthroughs that no single expert would discover alone.

## Non-Negotiable Gates
- **GATE 1 — Decomposition First**: NEVER analyze without decomposing first. The
  problem must be segmented into semantic chunks and core elements extracted before
  any domain identification begins.
- **GATE 2 — Multi-Lens Minimum**: ALWAYS generate at least 3 expert personas across
  different domains. Single-perspective analysis is forbidden.
- **GATE 3 — Evidence-Grounded**: Every breakthrough claim MUST be supported by
  research evidence gathered through Tavily searches. No unsubstantiated speculation.
- **GATE 4 — Cross-Domain Required**: The final synthesis MUST include at least 2
  cross-domain connections. If domains don't intersect, the decomposition was wrong.

## Pipeline Stages

### STAGE 1: DECOMPOSE
**Input**: User's problem/challenge description (minimum 50 characters)
**Process**:
1. Semantic segmentation — split into coherent chunks (<=300 chars each)
2. Element extraction — identify concepts, technologies, methodologies, challenges, opportunities
3. Complexity analysis — score tech/method/challenge/concept complexity → LOW/MEDIUM/HIGH
**Output**: Decomposition report with segments, elements, complexity level
**Gate**: complexity.totalComplexity determines depth (>20=AUTHORITY, >10=EXPERT, else=SPECIALIST)
**Error**: If input <50 chars → ask user to elaborate with guiding questions

### STAGE 2: IDENTIFY
**Input**: Decomposition report
**Process**:
1. Pattern-match segments against 19 domain indicators:
   Machine-Learning, Quantum-Computing, Blockchain, Biotechnology, Data-Engineering,
   Cybersecurity, Cloud-Architecture, NLP, Robotics, FinTech, Computer-Vision, IoT,
   AR-VR, DevOps, Infrastructure-Finance, Geopolitical-Infrastructure,
   Government-Contracting, Enterprise-Scaling, Sovereign-Wealth-Investment
2. Score domain confidence (0.0-1.0) per segment
3. Categorize: PRIMARY (>0.7), TECHNICAL (>0.4 + technical flag), ADJACENT (>0.2)
4. Identify subdomains within primary domains
5. Check Neo4j for existing domain mappings and related frameworks
**Output**: Domain map with primary, technical, adjacent, methodological domains
**Gate**: At least 2 primary domains identified. If <2, broaden analysis or ask user.
**Error**: If no domains score >0.4 → treat as General-Systems + ask user for domain hints

### STAGE 3: GENERATE
**Input**: Domain map + complexity level
**Process**:
1. Generate PRIMARY expert personas (one per primary domain):
   - Name: {Domain}-{DepthDescriptor} (e.g., "Machine-Learning-Authority")
   - Competencies: core, technical, methodological, analytical
   - Research approach: methods tuned to depth level
   - Query strategies: 4-7 Tavily search queries per persona
   - Collaboration style: role + approach
   - Perspective traits: focus, bias, blind spot
2. Generate SUBDOMAIN experts for high-confidence (>0.5) subdomains
3. Generate METHODOLOGY expert if methodological domains detected
4. Generate INTEGRATION ARCHITECT if 2+ primary domains exist
**Output**: Complete expert persona roster with query strategies
**Gate**: Minimum 3 personas. Integration Architect required if domains >1.

### -- CHECKPOINT 1: USER REVIEW --
Present to user:
- Domain map visualization (primary/technical/adjacent)
- Expert persona roster with expertise descriptions
- Proposed research focus areas
Ask: "Does this domain mapping capture your problem? Should I adjust any experts or add domains?"
Wait for user confirmation or adjustments before proceeding.

### STAGE 4: RESEARCH
**Input**: Expert personas + original context
**Process**:
1. For each persona, execute 3-5 Tavily searches using their query strategies
2. Apply domain-specific site filters (arxiv.org for ML, nature.com for biotech, etc.)
3. Use sequential thinking to analyze findings through each persona's lens
4. Cross-reference findings between related personas
5. Flag contradictions and unexpected connections
**Output**: Domain-specific research findings per persona
**Tools**: tavily_search (primary), deep_research (complex), arxiv_search (academic), patent_search (IP)
**Gate**: Minimum 10 total searches executed across all personas

### STAGE 5: DISCUSS
**Input**: Research findings from all personas
**Process**: Simulate 4-round expert panel discussion:
  Round 1 — Domain Presentations: Each persona presents 3-5 key findings
  Round 2 — Cross-Domain Connections: Personas identify synergies and conflicts
  Round 3 — Breakthrough Ideation: Collaborative breakthrough opportunity design
  Round 4 — Implementation Planning: Concrete next steps and resource requirements
**Output**: Expert discussion transcript with identified breakthroughs
**Conflict Resolution**: Evidence-based consensus. Integration Architect has final synthesis authority.
**Gate**: At least 2 cross-domain connections identified in Round 2

### STAGE 6: SYNTHESIZE
**Input**: Expert discussion output + research findings
**Process**:
1. Score breakthroughs: potential (0-10), feasibility (0-10), impact (0-10), time-to-value
2. Weight: breakthrough_potential=0.35, feasibility=0.25, impact=0.25, time_to_value=0.15
3. Rank opportunities by weighted score
4. Validate top 3 against evidence
5. Check Neo4j for existing breakthroughs or prior art
6. Generate cross-domain connection map
**Output**: Prioritized breakthrough list with evidence and scores
**Gate**: Top breakthrough must score >=6.0 weighted

### -- CHECKPOINT 2: USER REVIEW --
Present to user:
- Top 3-5 breakthrough opportunities with scores
- Cross-domain connection map
- Key evidence supporting each breakthrough
Ask: "Which breakthroughs resonate most? Should I develop implementation plans for specific ones?"

### STAGE 7: IMPLEMENT
**Input**: User-selected breakthroughs
**Process**:
1. For each selected breakthrough, design implementation pathway:
   - Phase 1 (0-3 months): Foundation actions
   - Phase 2 (3-6 months): Build milestones
   - Phase 3 (6-12 months): Scale targets
2. Identify resource requirements (technical, human, financial)
3. Map risks with mitigation strategies
4. Define success metrics and validation criteria
5. Write findings to Neo4j (with user confirmation)
**Output**: Implementation roadmap + Neo4j persistence

## Error Handling
| Error | Response |
|-------|----------|
| Input too short (<50 chars) | "I need more context. Can you describe the challenge in 2-3 sentences?" |
| No domains detected | "I'm not finding clear domain signals. What fields of expertise are most relevant?" |
| Search returns empty | Broaden queries, remove domain filters, try adjacent terms |
| Single domain only | "This looks single-domain. Want me to hand off to Domain Explorer for a deep dive?" |
| No breakthroughs | "Domains aren't intersecting strongly. Let me try different cross-domain combos." |
| User unclear on review | Present specific options: "(a) keep this, (b) add [domain], or (c) remove [persona]?" |

## Output Rules
- ALWAYS show the domain map before researching
- ALWAYS present personas with their expertise descriptions
- ALWAYS include evidence citations for breakthrough claims
- ALWAYS provide concrete implementation steps
- NEVER skip the 4-round discussion format
- NEVER claim a breakthrough without cross-domain evidence
- NEVER write to Neo4j without user confirmation
- Present expert perspectives using ThinkingPanel
"""


# =============================================================================
# COMPONENT B: CONVERSATION STARTERS
# =============================================================================

STARTERS = [
    cl.Starter(
        label="🧬 Decompose a Complex Challenge",
        message="I have a complex challenge that spans multiple domains. Help me break it down with expert analysis: ",
        icon="/public/icons/analyze.svg",
    ),
    cl.Starter(
        label="🔬 Analyze a Strategic Problem",
        message="Run the Expert Breakdown Engine on this strategic problem to identify breakthrough opportunities: ",
        icon="/public/icons/research.svg",
    ),
    cl.Starter(
        label="🧩 Show Me How It Works",
        message="Walk me through the Expert Breakdown process with an example. How does multi-domain expert decomposition work?",
        icon="/public/icons/example.svg",
    ),
    cl.Starter(
        label="🌐 Cross-Domain Breakthrough Discovery",
        message="I need to find hidden connections between different fields. Help me discover cross-domain breakthroughs in: ",
        icon="/public/icons/synthesize.svg",
    ),
]


# =============================================================================
# COMPONENT C: BOTS DICT ENTRY
# =============================================================================

BOTS_ENTRY = {
    "name": "Expert Breakdown",
    "icon": "🧬",
    "description": "Decompose complex problems into expert domains, generate personas, orchestrate multi-domain research, and synthesize cross-domain breakthroughs",
    "system_prompt": SYSTEM_PROMPT,
    "has_phases": True,
    "simple_mode": False,
    "welcome": """🧬 **Expert Breakdown Engine**
*Multi-Domain Expert Decomposition & Breakthrough Discovery*

I decompose complex challenges through a 7-stage pipeline:

```
DECOMPOSE → IDENTIFY → GENERATE → [You Review] → RESEARCH → DISCUSS → SYNTHESIZE → [You Review] → IMPLEMENT
```

**What I do:**
1. **Decompose** your problem into semantic segments and core elements
2. **Identify** the expertise domains your challenge spans (from 19+ fields)
3. **Generate** expert personas — virtual specialists for each domain
4. **Research** through each expert's lens using targeted web searches
5. **Simulate** a 4-round expert panel discussion
6. **Synthesize** cross-domain breakthrough opportunities
7. **Build** concrete implementation roadmaps

**You stay in control** — I pause at two checkpoints so you can review the domain mapping and validate breakthroughs before I proceed.

**To begin**, describe your challenge, strategic problem, or complex opportunity. The more context you provide, the richer the expert decomposition.

What complex problem should we break down?""",
}


# =============================================================================
# COMPONENT D: AGENT TRIGGERS
# =============================================================================

AGENT_TRIGGERS = {
    "keywords": [
        "expert breakdown",
        "break down",
        "decompose",
        "multi-domain",
        "expert analysis",
        "persona",
        "expert panel",
        "cross-domain",
        "domain mapping",
        "breakthrough discovery",
        "genesis",
        "multi-perspective",
        "expert synthesis",
        "domain identification",
        "complex challenge",
        "strategic decomposition",
    ],
    "description": "Decompose complex problems into expert domains and discover cross-domain breakthroughs",
}


# =============================================================================
# COMPONENT E: ACTION CALLBACK
# =============================================================================

@cl.action_callback("switch_to_expert_breakdown")
async def on_switch(action: cl.Action):
    await handle_agent_switch("expert_breakdown")


# =============================================================================
# COMPONENT F: PIPELINE PHASES
# =============================================================================

WORKSHOP_PHASES = [
    {
        "name": "Problem Intake & Decomposition",
        "status": "ready",
        "completion_keywords": [
            "segments identified", "elements extracted",
            "complexity scored", "decomposition complete",
        ],
        "goal": "Decompose the user's problem into semantic segments, extract core elements, and assess complexity level (LOW/MEDIUM/HIGH)",
        "stages": ["DECOMPOSE", "IDENTIFY", "GENERATE"],
    },
    {
        "name": "Domain Review & Expert Confirmation",
        "status": "pending",
        "completion_keywords": [
            "domains confirmed", "personas approved",
            "mapping accepted", "looks good", "proceed", "continue",
        ],
        "goal": "Present domain map and expert personas to user for review. Gate: user confirms before research begins.",
        "stages": ["CHECKPOINT_1"],
    },
    {
        "name": "Multi-Domain Research & Expert Discussion",
        "status": "pending",
        "completion_keywords": [
            "research complete", "discussion finished",
            "panel concluded", "findings ready",
        ],
        "goal": "Execute Tavily searches through each persona's lens and simulate 4-round expert panel discussion",
        "stages": ["RESEARCH", "DISCUSS"],
    },
    {
        "name": "Breakthrough Synthesis & Implementation",
        "status": "pending",
        "completion_keywords": [
            "breakthroughs ranked", "roadmap created",
            "implementation ready", "saved to graph",
        ],
        "goal": "Score and rank breakthroughs, present for user selection, generate implementation roadmaps",
        "stages": ["SYNTHESIZE", "CHECKPOINT_2", "IMPLEMENT"],
    },
]


# =============================================================================
# COMPONENT G: THINKINGPANEL COLOR
# =============================================================================

THINKING_COLOR = "#0f766e"  # Teal-700


# =============================================================================
# COMPONENT H: DYNAMIC EXAMPLES
# =============================================================================

BOT_TO_METHODOLOGY = [
    "Genesis Engine",
    "Multi-Domain Expert Decomposition",
    "Cross-Domain Breakthrough Synthesis",
    "Expert Persona Generation",
]

BOT_TO_CASE_TOPICS = [
    "Land Bridge Geopolitical Logistics",
    "AI-Powered Education Transformation",
    "Quantum Computing Drug Discovery",
    "Sustainable Infrastructure Finance",
]

STATIC_EXAMPLES = [
    "**Input**: 'How can a US company build a $2B land bridge connecting ports across a developing nation?'. "
    "**Decompose**: 7 segments, elements: {tech: infrastructure, logistics, ai; challenges: geopolitical risk, "
    "financing; opportunities: trade corridor, sovereignty}. Complexity: HIGH (24). "
    "**Identify**: Primary: Infrastructure-Finance (0.85), Geopolitical-Infrastructure (0.92), "
    "Government-Contracting (0.78). Technical: Enterprise-Scaling (0.65). "
    "**Generate**: 5 personas including Integration-Architect. "
    "**Research**: 18 Tavily searches. **Discuss**: 4-round panel → 4 breakthroughs. "
    "**Synthesize**: Top: 'Blended Finance + Sovereign Guarantee Structure' (8.2/10). "
    "**Implement**: Phase 1: MOU with host government (0-3mo), Phase 2: Sovereign fund partnerships (3-6mo).",

    "**Input**: 'How can quantum computing accelerate drug discovery for rare diseases?'. "
    "**Decompose**: 5 segments, Complexity: HIGH (22). "
    "**Identify**: Primary: Quantum-Computing (0.88), Biotechnology (0.91). Technical: Machine-Learning (0.72). "
    "**Generate**: 4 personas. Panel Round 2: 'VQE + protein folding = 10,000x speedup'. "
    "**Synthesize**: Top: 'Hybrid Quantum-Classical Pipeline for Molecular Docking' (8.6/10). "
    "Cross-domain: quantum error correction applied to genomic noise filtering.",

    "**Input**: 'Breakthrough opportunities at intersection of fintech and sustainability?'. "
    "**Decompose**: 4 segments, Complexity: MEDIUM (15). "
    "**Identify**: Primary: FinTech (0.82), Blockchain (0.71). Adjacent: IoT (0.35). "
    "**Generate**: 4 personas including FinTech-Blockchain-Integration-Architect. "
    "**Research**: 12 searches. Finding: carbon credit tokenization +340% YoY. "
    "**Synthesize**: Top: 'DeFi Carbon Credit Marketplace with IoT Verification' (7.8/10).",
]


# =============================================================================
# COMPONENT I: TOOL STACK
# =============================================================================

TOOLS = {
    "DECOMPOSE": ["langextract", "problem_classifier", "context_extraction"],
    "IDENTIFY": ["graphrag_lite", "neo4j_framework_discovery", "graph_router", "pws_brain"],
    "GENERATE": ["pws_brain", "dynamic_examples", "context_persistence"],
    "RESEARCH": ["tavily_search", "deep_research", "arxiv_search", "patent_search", "news_search", "trends_search", "research_cache"],
    "DISCUSS": ["result_synthesizer", "insight_extractor", "research_cache"],
    "SYNTHESIZE": ["assessment_engine", "opportunity_bank", "validation_workflow", "quality_scorer"],
    "IMPLEMENT": ["diagrams", "charts", "smart_phase_tracker", "phase_insights", "storage"],
}


# =============================================================================
# COMPONENT J: NEO4J QUERIES — GRAPH-GROUNDED
# =============================================================================

NEO4J_QUERIES = {
    "find_domain_experts": """
        MATCH (de:DomainExpert)
        WHERE de.focus CONTAINS $focus_term
        RETURN de.name, de.persona, de.expertise_depth, de.focus, de.key_queries
        LIMIT 10;
    """,
    "find_domain_analysis": """
        MATCH (da:DomainAnalysis)-[:MAPS_DOMAIN]->(dm:DomainMapping)
        WHERE da.analysis_type CONTAINS $analysis_type
        RETURN da.name, da.complexity_level, da.complexity_score,
               dm.domain, dm.confidence, dm.significance
        LIMIT 15;
    """,
    "find_breakthroughs": """
        MATCH (b:Breakthrough)
        WHERE b.scenario CONTAINS $scenario_term OR b.enables CONTAINS $scenario_term
        RETURN b.name, b.scenario, b.validation, b.enables
        LIMIT 10;
    """,
    "find_breakthrough_synthesis": """
        MATCH (bs:BreakthroughSynthesis)
        WHERE bs.core_insight CONTAINS $search_term
           OR bs.strategic_pivot CONTAINS $search_term
        RETURN bs.name, bs.core_insight, bs.value_creation,
               bs.strategic_pivot, bs.multiplier_effect
        LIMIT 5;
    """,
    "find_breakthrough_pathways": """
        MATCH (bp:BreakthroughPathway)
        WHERE bp.approach CONTAINS $approach_term
        RETURN bp.name, bp.timeframe, bp.approach, bp.opportunity, bp.barrier
        LIMIT 10;
    """,
    "find_cross_domain": """
        MATCH (cd:CrossDomain)
        WHERE cd.field CONTAINS $field_term OR cd.technique CONTAINS $field_term
        RETURN cd.name, cd.field, cd.technique, cd.relevance, cd.key_insight
        LIMIT 10;
    """,
    "find_innovation_tools": """
        MATCH (it:InnovationTool)
        WHERE any(wu IN it.when_use WHERE wu CONTAINS $use_case)
           OR it.purpose CONTAINS $use_case
        RETURN it.name, it.purpose, it.when_use, it.how_use, it.key_action
        LIMIT 8;
    """,
    "find_domain_frameworks": """
        MATCH (f:Framework)
        WHERE f.name CONTAINS $domain_term OR f.framework_type CONTAINS $domain_term
        RETURN f.name, f.framework_type, f.principles
        LIMIT 10;
    """,
    "find_domain_neighbors": """
        MATCH (dm:DomainMapping)-[r]-(neighbor)
        WHERE dm.domain CONTAINS $domain_name
        RETURN dm.domain, type(r) as rel_type,
               labels(neighbor) as neighbor_labels, neighbor.name as neighbor_name
        LIMIT 20;
    """,
    "detect_domain_gaps": """
        MATCH (da:DomainAnalysis)
        WHERE NOT (da)-[:MAPS_DOMAIN]->(:DomainMapping)
        RETURN da.name, da.complexity_level, da.analysis_type
        LIMIT 10;
    """,
    "find_prior_art": """
        MATCH (dm1:DomainMapping), (dm2:DomainMapping)
        WHERE dm1.domain CONTAINS $domain_a AND dm2.domain CONTAINS $domain_b
          AND dm1 <> dm2
        OPTIONAL MATCH (dm1)<-[:MAPS_DOMAIN]-(da:DomainAnalysis)-[:MAPS_DOMAIN]->(dm2)
        RETURN dm1.domain, dm2.domain, da.name as shared_analysis, da.complexity_level
        LIMIT 5;
    """,
    "get_analysis_experts": """
        MATCH (da:DomainAnalysis)-[:CONSULTED_EXPERT]->(de:DomainExpert)
        WHERE da.id = $analysis_id
        RETURN da.name as analysis, de.name, de.persona, de.expertise_depth, de.focus, de.key_queries
        LIMIT 20;
    """,
    "get_domain_map": """
        MATCH (dmap:DomainMap)
        WHERE dmap.name CONTAINS $map_name
        OPTIONAL MATCH (dmap)-[r]-(related)
        RETURN dmap.name, dmap.created, type(r) as rel_type,
               labels(related) as related_labels, related.name as related_name
        LIMIT 30;
    """,
}


# =============================================================================
# COMPONENT K: NEO4J WRITE TEMPLATES
# =============================================================================

NEO4J_WRITES = {
    "create_domain_analysis": """
        MERGE (da:DomainAnalysis {id: $analysis_id})
        SET da.name = $name, da.analysis_type = $analysis_type,
            da.complexity_level = $complexity_level, da.complexity_score = $complexity_score,
            da.added_by = 'expert-breakdown-agent', da.added_date = date()
        RETURN da.name, da.id;
    """,
    "create_domain_mapping": """
        MERGE (dm:DomainMapping {name: $name})
        SET dm.domain = $domain, dm.confidence = $confidence,
            dm.significance = $significance, dm.addressed = $addressed,
            dm.key_assumptions = $key_assumptions, dm.critical_omissions = $critical_omissions,
            dm.added_by = 'expert-breakdown-agent', dm.added_date = date()
        RETURN dm.name, dm.domain;
    """,
    "link_analysis_to_mapping": """
        MATCH (da:DomainAnalysis {id: $analysis_id})
        MATCH (dm:DomainMapping {name: $mapping_name})
        MERGE (da)-[r:MAPS_DOMAIN]->(dm)
        SET r.added_by = 'expert-breakdown-agent', r.added_date = date()
        RETURN da.name, dm.domain;
    """,
    "create_domain_expert": """
        MERGE (de:DomainExpert {name: $name})
        SET de.persona = $persona, de.expertise_depth = $expertise_depth,
            de.focus = $focus, de.key_queries = $key_queries,
            de.added_by = 'expert-breakdown-agent', de.added_date = date()
        RETURN de.name, de.persona;
    """,
    "link_analysis_to_expert": """
        MATCH (da:DomainAnalysis {id: $analysis_id})
        MATCH (de:DomainExpert {name: $expert_name})
        MERGE (da)-[r:CONSULTED_EXPERT]->(de)
        SET r.added_by = 'expert-breakdown-agent', r.added_date = date()
        RETURN da.name, de.persona;
    """,
    "create_breakthrough": """
        MERGE (b:Breakthrough {name: $name})
        SET b.scenario = $scenario, b.validation = $validation,
            b.enables = $enables,
            b.added_by = 'expert-breakdown-agent', b.added_date = date()
        RETURN b.name, b.scenario;
    """,
    "create_breakthrough_pathway": """
        MERGE (bp:BreakthroughPathway {name: $name})
        SET bp.timeframe = $timeframe, bp.approach = $approach,
            bp.opportunity = $opportunity, bp.barrier = $barrier,
            bp.added_by = 'expert-breakdown-agent', bp.added_date = date()
        RETURN bp.name, bp.timeframe;
    """,
    "create_cross_domain": """
        MERGE (cd:CrossDomain {name: $name})
        SET cd.field = $field, cd.technique = $technique,
            cd.relevance = $relevance, cd.key_insight = $key_insight,
            cd.added_by = 'expert-breakdown-agent', cd.added_date = date()
        RETURN cd.name, cd.field;
    """,
    "batch_create_mappings": """
        UNWIND $mappings AS m
        MERGE (dm:DomainMapping {name: m.name})
        SET dm.domain = m.domain, dm.confidence = m.confidence,
            dm.significance = m.significance, dm.addressed = false,
            dm.added_by = 'expert-breakdown-agent', dm.added_date = date()
        RETURN count(dm) AS created;
    """,
    "rollback_today": """
        MATCH (n)
        WHERE n.added_by = 'expert-breakdown-agent' AND n.added_date = date()
        DETACH DELETE n
        RETURN count(n) AS deleted;
    """,
}


# =============================================================================
# COMPONENT L: SUB-AGENTS
# =============================================================================

SUB_AGENTS = {
    "decomposer": {
        "name": "Context Decomposer",
        "role": "Semantic segmentation and element extraction from problem descriptions",
        "trigger": "When user provides a new problem or challenge to analyze",
        "prompt_suffix": "You are the Context Decomposer. Break down the problem into semantic segments (<=300 chars), extract core elements (concepts, technologies, methodologies, challenges, opportunities), and assess complexity. Report segment count, element counts, complexity level (LOW/MEDIUM/HIGH).",
        "tools": ["langextract", "problem_classifier", "context_extraction"],
    },
    "domain_scout": {
        "name": "Domain Scout",
        "role": "Pattern-match segments against 19+ expertise domains and score confidence",
        "trigger": "After decomposition is complete",
        "prompt_suffix": "You are the Domain Scout. Analyze segments against 19 domain indicators. Score confidence (0.0-1.0). Categorize: PRIMARY (>0.7), TECHNICAL (>0.4), ADJACENT (>0.2). Identify subdomains. Check Neo4j for existing mappings. Minimum 2 primary domains.",
        "tools": ["graphrag_lite", "neo4j_framework_discovery", "graph_router"],
    },
    "persona_architect": {
        "name": "Persona Architect",
        "role": "Generate expert personas with competencies, research strategies, and collaboration styles",
        "trigger": "After domain identification",
        "prompt_suffix": "You are the Persona Architect. Per domain generate: name ({Domain}-{Depth}), competencies (core, technical, methodological, analytical), research approach, 4-7 Tavily queries, collaboration style, perspective traits. Integration Architect if 2+ domains. Minimum 3 personas.",
        "tools": ["pws_brain", "dynamic_examples"],
    },
    "research_coordinator": {
        "name": "Research Coordinator",
        "role": "Execute multi-persona Tavily searches and cross-reference findings",
        "trigger": "After user confirms domain mapping",
        "prompt_suffix": "You are the Research Coordinator. Per persona execute 3-5 Tavily searches with domain-specific filters. Analyze through each persona's lens. Cross-reference findings. Flag contradictions and connections. Minimum 10 total searches.",
        "tools": ["tavily_search", "deep_research", "arxiv_search", "patent_search", "news_search", "research_cache"],
    },
    "panel_facilitator": {
        "name": "Panel Facilitator",
        "role": "Simulate 4-round expert panel discussion and identify breakthroughs",
        "trigger": "After research is complete",
        "prompt_suffix": "You are the Panel Facilitator. Run 4 rounds: 1) Presentations, 2) Cross-domain connections, 3) Breakthrough ideation, 4) Implementation planning. Maintain authentic voices. Document disagreements. Minimum 2 cross-domain connections.",
        "tools": ["result_synthesizer", "insight_extractor"],
    },
    "synthesis_engine": {
        "name": "Synthesis Engine",
        "role": "Score, rank, and validate breakthrough opportunities",
        "trigger": "After expert panel discussion",
        "prompt_suffix": "You are the Synthesis Engine. Score: potential (0-10), feasibility (0-10), impact (0-10), time-to-value. Weights: 0.35/0.25/0.25/0.15. Validate top 3. Check Neo4j for prior art. Top must score >=6.0.",
        "tools": ["assessment_engine", "opportunity_bank", "validation_workflow", "quality_scorer"],
    },
}


# =============================================================================
# COMPONENT M: SCRIPT MANIFEST & DEPENDENCIES
# =============================================================================

SCRIPT_MANIFEST = {
    "decompose_context": {
        "file": "scripts/decompose_context.py",
        "stage": 1,
        "purpose": "Semantic segmentation and element extraction from problem text",
        "input": "Raw text (.txt) or JSON with 'text'/'content' key",
        "output": "decomposition.json — segments, elements, complexity assessment",
        "cli": "python scripts/decompose_context.py input.txt [output.json] [--max-segment 300]",
        "importable": "from scripts.decompose_context import decompose_context",
    },
    "identify_domains": {
        "file": "scripts/identify_domains.py",
        "stage": 2,
        "purpose": "Pattern-match segments against 19+ expertise domains",
        "input": "decomposition.json (Stage 1 output)",
        "output": "domains.json — primary, technical, adjacent, methodological domains",
        "cli": "python scripts/identify_domains.py decomposition.json [domains.json]",
        "importable": "from scripts.identify_domains import identify_domains",
    },
    "generate_personas": {
        "file": "scripts/generate_personas.py",
        "stage": 3,
        "purpose": "Create expert personas with competencies and research strategies",
        "input": "domains.json (Stage 2) + decomposition.json (Stage 1)",
        "output": "personas.json — expert roster with query strategies",
        "cli": "python scripts/generate_personas.py domains.json decomposition.json [personas.json]",
        "importable": "from scripts.generate_personas import generate_personas",
    },
    "orchestrate_research": {
        "file": "scripts/orchestrate_research.py",
        "stage": 4,
        "purpose": "Build collaboration matrix and research execution plan",
        "input": "personas.json (Stage 3) + optional context.txt",
        "output": "research_plan.json — phases, interactions, quality controls, synthesis strategy",
        "cli": "python scripts/orchestrate_research.py personas.json [research_plan.json] [--context challenge.txt]",
        "importable": "from scripts.orchestrate_research import orchestrate_research",
    },
    "synthesize_breakthroughs": {
        "file": "scripts/synthesize_breakthroughs.py",
        "stage": 6,
        "purpose": "Score, validate, rank, and roadmap breakthrough opportunities",
        "input": "findings.json (expert panel output with 'breakthroughs' key)",
        "output": "synthesis.json — scored breakthroughs with implementation roadmaps",
        "cli": "python scripts/synthesize_breakthroughs.py findings.json [synthesis.json] [--min-score 5.0] [--max-breakthroughs 5]",
        "importable": "from scripts.synthesize_breakthroughs import synthesize_breakthroughs",
    },
}

DEPENDENCIES = [
    # All stdlib — no pip packages required
    "json",         # JSON I/O
    "re",           # Regex pattern matching
    "sys",          # System exit
    "argparse",     # CLI argument parsing
    "datetime",     # Timestamps
    "collections",  # Counter for domain scoring
    "itertools",    # combinations for pairwise interactions
]


# =============================================================================
# COMPONENTS N-O: MEDIA PLACEHOLDERS
# =============================================================================

VIDEO_URLS = {"intro": "", "tutorial": ""}
AUDIOBOOK_CHAPTERS = {"genesis_overview": ""}
